### ISSUE TITLE
Updates following feedback

### ISSUE THREAD

**Issue by HannahSones** [HannahSones/CodeRefactor#1]
@StevenRafferty, @sol3uk code updated following feedback.
Bugs fixed:
- anchor links in the nav bar
- semantic HTML used throughout
- alt attributes added to all images

**Comment by sol3uk** [comment]
Brilliant @HannahSones, this looks much better now.
Only thing I would mention is that you didn't use <main> anywhere but I think as you are using <section> instead is arguably the same if not better.

**Comment by HannahSones** [comment]
@sol3uk Thanks Ben.
